export const REQUEST_START = 'REQUEST_START';

export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_FAILURE = 'CREATE_BOARD_FAILURE';

export const DISPLAY_BOARDS_SUCCESS = 'DISPLAY_BOARDS_SUCCESS';
export const DISPLAY_BOARDS_FAILURE = 'DISPLAY_BOARDS_FAILURE';
export const DISPLAY_BOARD_SUCCESS = 'DISPLAY_BOARD_SUCCESS';
export const DISPLAY_BOARD_FAILURE = 'DISPLAY_BOARD_FAILURE';

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

