export const REQUEST_START = 'REQUEST_START';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const CREATE_USER_PROFILE_SUCCESS =  'CREATE_USER_PROFILE_SUCCESS';
export const CREATE_USER_PROFILE_FAILURE = 'CREATE_USER_PROFILE_FAILURE';

export const DISPLAY_USER_PROFILE_SUCCESS = 'DISPLAY_USER_PROFILE_SUCCESS';
export const DISPLAY_USER_PROFILE_FAILURE = 'DISPLAY_USER_PROFILE_FAILURE';
